"""
Django settings for car_manager project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads .env for local development (see .env.example). No-op if the file
# doesn't exist, so this is safe in production, where real env vars are set
# through the hosting provider instead of a committed/local file.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a missing env var in production fails closed instead
# of silently exposing debug info (stack traces, settings, SQL).
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# The "django-insecure-" fallback is ONLY for local development (matches the
# key django-admin generates for a fresh project). In production DEBUG=False,
# so a missing DJANGO_SECRET_KEY raises instead of falling back silently.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-n(m^h+b%6)al$s8a(_#b^v+owjcl-&hou)fvh5+vfw)wx)j$6h"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY environment variable must be set when DEBUG=False."
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,.vercel.app"
    ).split(",")
    if host.strip()
]

# Hardening applied only in production (DEBUG=False). Left off locally so
# `runserver` over plain HTTP still works without extra config.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True").lower() == "true"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Vercel terminates TLS in front of the app and forwards this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Without this, axes reads REMOTE_ADDR, which behind Vercel's proxy is
    # Vercel's own edge address for every request - every visitor would share
    # one lockout bucket. Telling it there's exactly one proxy hop makes it
    # read the real client IP from X-Forwarded-For instead.
    AXES_IPWARE_PROXY_COUNT = 1


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "axes",
    "cars",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",  # has to stay last
]

# django-axes locks out a username+IP pair after too many failed logins.
# Hooks in through AUTHENTICATION_BACKENDS, so it covers both the custom
# /auth/login/ endpoint and the built-in /admin/login/ without touching
# either view - neither had any brute-force protection before this.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",  # has to stay first
    "django.contrib.auth.backends.ModelBackend",
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]

ROOT_URLCONF = "car_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "car_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# SQLite is fine for local development, but Vercel's serverless functions have
# an ephemeral filesystem: a SQLite file written there does not survive
# between deploys (or reliably between invocations), so any data entered in
# that environment can vanish. Set DATABASE_URL (e.g. to a managed Postgres
# instance from Neon/Supabase) to use a real database there instead; SQLite
# stays the default so local dev needs no extra setup.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# axes logs every failed login attempt at INFO level, which drowns out
# `manage.py test` output. The lockouts themselves are still recorded either way.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "loggers": {
        "axes": {"level": "WARNING"},
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Source directory for hand-authored static assets (css/theme.css, favicon, the
# compiled SPA bundle). Registered so `{% static %}` resolves both locally via
# `runserver` (DEBUG=True) and through the explicit /static/ route added in
# car_manager/urls.py for the Vercel deployment, which has no collectstatic step.
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
