# Generated by Django 4.2.7 on 2025-07-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="maintenance",
            options={"ordering": ["-service_date"]},
        ),
        migrations.AddField(
            model_name="car",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="expense",
            name="mileage",
            field=models.IntegerField(blank=True, null=True, verbose_name="Mileage"),
        ),
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="service_provider",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Service Provider"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(max_length=30, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="car",
            name="current_mileage",
            field=models.IntegerField(verbose_name="Current Mileage"),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("gasoline", "Gasoline"),
                    ("diesel", "Diesel"),
                    ("hybrid", "Hybrid"),
                    ("electric", "Electric"),
                ],
                max_length=20,
                verbose_name="Fuel Type",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="license_plate",
            field=models.CharField(max_length=20, verbose_name="License Plate"),
        ),
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.CharField(max_length=50, verbose_name="Make"),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=50, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Amount ($)"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="cars.car",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("fuel", "Fuel"),
                    ("maintenance", "Maintenance"),
                    ("insurance", "Insurance"),
                    ("registration", "Registration"),
                    ("parking", "Parking"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenances",
                to="cars.car",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Cost ($)"
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="mileage_at_service",
            field=models.IntegerField(verbose_name="Mileage at Service"),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="service_date",
            field=models.DateField(verbose_name="Service Date"),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="service_name",
            field=models.CharField(max_length=200, verbose_name="Service Name"),
        ),
    ]
