# Generated by Django 4.2.7 on 2026-03-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_make_alter_car_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="fleet_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Fleet Name"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="car",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("taxi", "Taxi"),
                    ("fleet", "Fleet"),
                    ("delivery", "Delivery"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=20,
                verbose_name="Usage Type",
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_mileage", models.IntegerField(verbose_name="Start Mileage")),
                ("end_mileage", models.IntegerField(verbose_name="End Mileage")),
                (
                    "distance_km",
                    models.IntegerField(default=0, verbose_name="Distance (km)"),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Income ($)",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("taxi", "Taxi"),
                            ("delivery", "Delivery"),
                            ("ride_share", "Ride Share"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Trip Type",
                    ),
                ),
                (
                    "passengers",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Passengers"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("odometer", models.IntegerField(verbose_name="Odometer")),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Liters"
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Price per Liter ($)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Cost ($)"
                    ),
                ),
                (
                    "full_tank",
                    models.BooleanField(default=True, verbose_name="Full Tank"),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Station"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_records",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
