# Generated by Django 4.2.7 on 2026-08-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_fleet_name_car_is_active_car_usage_type_trip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="license_plate",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="License Plate"
            ),
        ),
    ]
